INSERT INTO ROLES (name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO ROLES (name) VALUES ('ROLE_INSTITUTION') ON CONFLICT DO NOTHING;
INSERT INTO ROLES (name) VALUES ('ROLE_COMPANY') ON CONFLICT DO NOTHING;