SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE companies RESTART IDENTITY;
TRUNCATE TABLE signups RESTART IDENTITY;
TRUNCATE TABLE schedule RESTART IDENTITY;
TRUNCATE TABLE user_roles RESTART IDENTITY;
TRUNCATE TABLE institutions RESTART IDENTITY;
TRUNCATE TABLE files RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;

